### ISSUE TITLE
about  the data path

### ISSUE THREAD

**Issue by crazygirl1992** [xxbb1234021/speech_recognition#1]
你好，你的conf文件夹内的路径我不太明白，label_file 具体是什么呀，还有wave_path 是你从清华数据集里面调出来的么，万分感谢

**Comment by xxbb1234021** [comment]
https://pan.baidu.com/s/1skGXz8x#list/path=%2F
label_file表示的是test.word.txt
wave_path是声音文件的路劲，语音文件中的test.zip解压即可
