### ISSUE TITLE
请问大神 跑是跑起来了 但是用训练好的模型怎么识别不在训练内的语音文件呢？

### ISSUE THREAD

**Issue by a2741432** [xxbb1234021/speech_recognition#10]
训练好的模型怎么识别不在训练内的语音文件呢？比如我目前训练了清华大学中文语料库（thchs30），现在我自己说一句话怎么识别？一换语音文件测试就报错了呢

**Comment by xxbb1234021** [comment]
自己录音，参考test.py最后4段代码

**Comment by JingangLang** [comment]
运行最后的四行代码报错啊，博主。  哦  不，运行5行。这是怎么回事呢？
`wav_files = ['./data/test/temp/D4/D4_750.wav']

text_labels = ['东北军 的 一些 爱国 将士 马 占 山 李杜 唐 聚 伍 苏 炳 艾 邓 铁梅 等 也 奋起 抗战']

words_size, words, word_num_map = utils.create_dict(text_labels)

bi_rnn = BiRNN(wav_files, text_labels, words_size, words, word_num_map)

bi_rnn.build_target_wav_file_test(wav_files, text_labels)`

**Comment by secsilm** [comment]
请问测试还需要提供 `test_label`？

**Comment by songran** [comment]
兄弟我是搞php的，python不是很懂，就是下载语料库后 你的config是怎么配置的？麻烦发下你的config配置

**Comment by sunjunlishi** [comment]
都是cpu，能不能 跑cpu的呀。

**Comment by zhouhao-learning** [comment]
大家千万别相信他的结果，这个所谓的"准确"其实是作弊的方式得来的，大家可以随便测试，只要是自己录制的声音，哪怕你照着标签念一遍，你就会发现，这预测结果很狗屎，无论你用什么设备录制，真不知道，靠这种把式弄这么个结果有啥意思，大家看到这个语音识别就请绕道把，一点鸟用没有，别浪费时间

**Comment by a2741432** [comment]
放弃了 效果不行
