### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by wangguojim** [xxbb1234021/speech_recognition#11]
楼主，您好。初学者有几个问题请教
   test.world.txt文件里放的是wav里的所有中文数据吗？顺序必须一致吗？还有测试的时候wave_files是文件名？还是？我调用文件名好像不对。

**Comment by xxbb1234021** [comment]
这里可以debug一下加载wav文件那段代码了解对应关系

**Comment by wangguojim** [comment]
谢谢，这个看明白了，但是测试时，输出是这样的，请问是什么原因

读入语音文件:  opt/wav/D11_751.wav
开始识别语音数据......
语音原始文本: 东北军 的 一些 爱国 将士 马 占 山 李杜 唐 聚 伍 苏 炳 艾 邓 铁梅 等 也 奋起 抗战
识别出来的文本:

**Comment by wangguojim** [comment]
谢谢，这个看明白了，但是测试时，输出是这样的，

读入语音文件: opt/wav/D11_751.wav
开始识别语音数据......
语音原始文本: 东北军 的 一些 爱国 将士 马 占 山 李杜 唐 聚 伍 苏 炳 艾 邓 铁梅 等 也 奋起 抗战
识别出来的文本:

识别出来的文本是空的，请问是什么原因？

**Comment by wangguojim** [comment]
谢谢，这个明白了

读入语音文件:  opt/wav\D11_763.wav
开始识别语音数据......
语音原始文本: 这个 电站 设计 安装 五台 机组 总 装机容量 两百万 千瓦 年 平均 发电量 五十九 亿 度
识别出来的文本:   的 

请问这是因为训练不够吗？所有的测试都只返回了一个“的”

**Comment by wangguojim** [comment]
谢谢，解决了
