### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by ZeR0ll** [xxbb1234021/speech_recognition#13]
I've try several ways to test my custom test audio file including use last 4 lines in test.py(actually it's 5 line) and change file location in conf.ini and none of these work for me,I think it's a code problem and I cant find the reason now,you did a really good job build this mandarin speech model! please fix test problem and make it better!

**Comment by sunshinepython** [comment]
您好，请问这个测试时是哪里出问题了，您找到解决方法了吗 @ZeR0ll
