### ISSUE TITLE
这个模型是否适用于识别简短的词语短语而非语句呢？

### ISSUE THREAD

**Issue by ChengYuXiang** [xxbb1234021/speech_recognition#14]
当我模型训练完毕以后，是否可以用于识别简短的词语（长度为：2~5的汉字）？

**Comment by yumath** [comment]
@ChengYuXiang 请问你有没有尝试识别短文本语音，如果尝试了，请问效果如何，多谢。

**Comment by 79168089** [comment]
是github吗？我只是看看，还没仔细研究呢


 
---原始邮件---
发件人: "longfish"<notifications@github.com>
发送时间: 2019年6月3日(星期一) 下午3:21
收件人: "xxbb1234021/speech_recognition"<speech_recognition@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [xxbb1234021/speech_recognition] 这个模型是否适用于识别简短的词语短语而非语句呢？ (#14)



@ChengYuXiang 请问你有没有尝试识别短文本语音，如果尝试了，请问效果如何，多谢。
